### ISSUE TITLE
Possible to create an uninitialized stat?

### ISSUE THREAD

**Issue by bscan** [uperl/FFI-C-Stat#9]
Hi, thanks for all your work on creating the FFI:: set of modules. I was wondering if it's possible to create an uninitialized or even zero-initialized `FFI::C::Stat` object. Specifically, I'm trying to use `smbc_stat` (from libsmbclient.h) which looks exactly like the examples in your documentation, where I have a function that requires a pointer to a stat as an input. However, `FFI::C::Stat` seems to always perform a variant of stat, or require an existing stat.

C function definition:
```c
/**
 * @param st        pointer to a buffer that will be filled with
 *                  standard Unix struct stat information.
*/
int smbc_stat(const char *url, struct stat *st);
```

The following Perl code successfully runs and performs the stat, but something seems odd about my explicit use of malloc and the hardcoded number of bytes. Although it works, I'm wondering if I am using this module incorrectly. I'm certainly no FFI expert. 
``` perl
...

$ffi->type('object(FFI::C::Stat)' => 'stat');
$ffi->attach( 'smbc_stat' => ['string', 'stat'] => 'int' );

...

my $ptr = malloc(144); # Number of bytes found in C with:  printf("Size of struct stat: %lu bytes\n", sizeof(struct stat));
my $stat = FFI::C::Stat->clone($ptr);
free $ptr;
my $result = smbc_stat($url, $stat);
 ```

Thanks!

**Comment by plicease** [comment]
Yes that code is correct and works for the platform that you are running on, but it won't be portable if you need the code to run on platforms where stat is a different size (and it can and does vary).

There should be a way to construct an uninitialized stat though this is a thing that is missing from the interface.  I'm thinking that calling `new` with no arguments should do exactly that:

```perl
  my $stat = FFI::C::Stat->new;
```

Since that is currently an error it will complain and die if you try to do that with an old version of FFI::C::Stat instead of silently erroring or corrupting memory.

Thank you for reporting this.

**Comment by plicease** [comment]
I think #10 will do what you need.

**Comment by plicease** [comment]
release #10 as 0.03.  Let me know if you have any questions.

**Comment by bscan** [comment]
Awesome, thanks! I just updated to 0.03 and it works for me with `smbc_stat`. Thank you for taking a look and for the fast turnaround on this.
